### PR TITLE
Add translate to belarusian language

### PR DESCRIPTION
**Pull request by lesh6295-png**
Although I live in Belarus, I practically do not use the Belarusian language, which is why the translation may be bad...

### CODE REVIEW

**Comment by khoadng** [comment]
Thanks.

It seems like a pain to keep these files in sync...
I wonder if there is a better solution.

**Comment by khoadng** [comment]
@lesh6295-png 
You might need to create a PR for Belarusian in this [repo](https://github.com/andresaraujo/timeago.dart), my use this package for human readable DateTime string.

**Comment by lesh6295-png** [comment]
I created translate to libary on Belarusian and open a [pull request](https://github.com/andresaraujo/timeago.dart/pull/197l), but i don`t known when it will added to main repo

**Comment by khoadng** [comment]
I will leave this PR open until that then

**Comment by khoadng** [comment]
Don't worry, I will update the code when that PR is merged.

**Comment by khoadng** [comment]
@lesh6295-png 
Is it okay to use Russian in place of Belarusian in the mean time? I mean is it acceptable?

**Comment by lesh6295-png** [comment]
@khoadng
Yes, difference will be a small

**Comment by khoadng** [comment]
aight i'll include it in the next update

**Comment by khoadng** [comment]
Also you forgot to include this in `be.json`
https://github.com/khoadng/Boorusama/blob/53b5f68ac16828829650eae308958607ebf2d0b3/assets/translations/en.json#L190

https://github.com/khoadng/Boorusama/blob/53b5f68ac16828829650eae308958607ebf2d0b3/assets/translations/be.json#L185-L190

**Comment by lesh6295-png** [comment]
@khoadng
Oh, sorry. I fix this and create a [pull request](https://github.com/khoadng/Boorusama/pull/78)

**Pull request merged**
